const seedProducts=[
 {id:1,name:'ELF BAR Combo',category:'Одноразовые',flavor:'Арбуз · лёд',price:1290,stock:12,badge:'ХИТ',color:'#bd45f4',popular:10},
 {id:2,name:'WAKA SoPro',category:'Одноразовые',flavor:'Манго · маракуйя',price:1490,stock:8,badge:'NEW',color:'#ff7146',popular:9},
 {id:3,name:'Chaser Black',category:'Жидкости',flavor:'Чёрная смородина',price:890,stock:17,badge:'',color:'#724fe7',popular:8},
 {id:4,name:'XROS 4 Mini',category:'Устройства',flavor:'Graphite',price:2990,stock:5,badge:'NEW',color:'#f0509f',popular:7},
 {id:5,name:'VooPoo Argus',category:'Устройства',flavor:'Space Grey',price:3990,stock:3,badge:'ХИТ',color:'#fb873d',popular:10},
 {id:6,name:'XROS Cartridge',category:'Расходники',flavor:'0.8 Ω · 2 мл',price:590,stock:24,badge:'',color:'#4ebacb',popular:6},
 {id:7,name:'Brusko Salt',category:'Жидкости',flavor:'Клубника · киви',price:990,stock:0,badge:'',color:'#f14d68',popular:5},
 {id:8,name:'Lost Mary BM',category:'Одноразовые',flavor:'Черника · малина',price:1390,stock:9,badge:'ХИТ',color:'#8c45ec',popular:8}
];
const storedProducts=JSON.parse(localStorage.getItem('ph-products')||'null');
const state={products:storedProducts?.some(p=>p.price<500)?seedProducts:storedProducts||seedProducts,cart:JSON.parse(localStorage.getItem('ph-cart')||'{}'),favorites:JSON.parse(localStorage.getItem('ph-favs')||'[]'),orders:JSON.parse(localStorage.getItem('ph-orders')||'[]'),category:'Все',search:'',maxPrice:5000,inStock:false,sort:'popular'};
const $=(s,root=document)=>root.querySelector(s), $$=(s,root=document)=>[...root.querySelectorAll(s)];
function save(){localStorage.setItem('ph-products',JSON.stringify(state.products));localStorage.setItem('ph-cart',JSON.stringify(state.cart));localStorage.setItem('ph-favs',JSON.stringify(state.favorites));localStorage.setItem('ph-orders',JSON.stringify(state.orders));}
function money(n){return `${new Intl.NumberFormat('ru-RU').format(n)} ₽`} function product(id){return state.products.find(p=>p.id===Number(id))}
function toast(t){const el=$('#toast');el.textContent=t;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),1800)}
function categories(){return ['Все',...new Set(state.products.map(p=>p.category))]}
function renderChips(){ $('#categoryChips').innerHTML=categories().map(c=>`<button class="${state.category===c?'active':''}" data-category="${c}">${c}</button>`).join(''); }
function visibleProducts(list=state.products){let out=list.filter(p=>(state.category==='Все'||p.category===state.category)&&p.price<=state.maxPrice&&(!state.inStock||p.stock>0)&&(`${p.name} ${p.flavor}`.toLowerCase().includes(state.search.toLowerCase())));return out.sort((a,b)=>state.sort==='priceAsc'?a.price-b.price:state.sort==='priceDesc'?b.price-a.price:state.sort==='new'?b.id-a.id:b.popular-a.popular)}
function card(p){return `<article class="product-card" data-product="${p.id}"><button class="fav ${state.favorites.includes(p.id)?'active':''}" data-fav="${p.id}">${state.favorites.includes(p.id)?'♥':'♡'}</button>${p.badge?`<span class="badge ${p.badge==='ХИТ'?'hit':''}">${p.badge}</span>`:''}<div class="product-art" style="--art:${p.color}"></div><div class="product-info"><h3>${p.name}</h3><p>${p.flavor}${p.stock?'':' · нет в наличии'}</p><div class="product-foot"><b>${money(p.price)}</b><button class="add-btn" data-add="${p.id}" ${p.stock?'':'disabled'}>+</button></div></div></article>`}
function renderProducts(){const out=visibleProducts();$('#productGrid').innerHTML=out.map(card).join('')||'<div class="empty">Ничего не найдено. Попробуйте изменить фильтры.</div>';const favs=state.products.filter(p=>state.favorites.includes(p.id));$('#favoritesGrid').innerHTML=favs.map(card).join('')||'<div class="empty">Здесь появятся товары, которые вы отметите сердцем.</div>'}
function addCart(id){const p=product(id);if(!p||!p.stock)return;state.cart[id]=Math.min((state.cart[id]||0)+1,p.stock);save();renderCart();toast('Добавлено в корзину')}
function renderCart(){const entries=Object.entries(state.cart).filter(([id,q])=>q&&product(id));const count=entries.reduce((s,[,q])=>s+q,0);$('#cartBadge').textContent=count;$('#cartItems').innerHTML=entries.map(([id,q])=>{const p=product(id);return `<div class="cart-item"><div class="cart-thumb" style="--art:${p.color}"></div><div><h3>${p.name}</h3><p>${p.flavor} · ${money(p.price)}</p></div><div class="qty"><button data-qty="${id}" data-delta="-1">−</button><b>${q}</b><button data-qty="${id}" data-delta="1">+</button></div></div>`}).join('')||'<div class="empty">Корзина пока пуста.</div>';const total=entries.reduce((s,[id,q])=>s+product(id).price*q,0);$('#subtotal').textContent=money(total);$('#cartTotal').textContent=money(total);$('#cartSummary').style.display=entries.length?'block':'none';document.dispatchEvent(new CustomEvent('parhub:cartchange',{detail:{count,total}}))}
function openProduct(id){const p=product(id);$('#productModalBody').innerHTML=`<button class="modal-close" data-close="productModal">×</button><div class="modal-art" style="--art:${p.color}"></div><p class="eyebrow" style="margin-top:18px">${p.category.toUpperCase()}</p><h2>${p.name}</h2><p class="muted">${p.flavor} · ${p.stock?`в наличии ${p.stock} шт.`:'нет в наличии'}</p><p class="muted">Яркий вкус, удобный формат и проверенное качество от PAR HUB.</p><div class="modal-price">${money(p.price)}</div><button class="primary" data-add="${p.id}" ${p.stock?'':'disabled'}>${p.stock?'Добавить в корзину':'Нет в наличии'}</button>`;$('#productModal').classList.add('open');document.dispatchEvent(new CustomEvent('parhub:modalchange'))}
function setView(name){$$('.view').forEach(v=>v.classList.remove('active'));$(`#${name}View`).classList.add('active');$$('.bottom-nav button').forEach(b=>b.classList.toggle('active',b.dataset.view===name));if(name==='admin')renderAdmin();window.scrollTo(0,0);document.dispatchEvent(new CustomEvent('parhub:viewchange',{detail:{view:name}}))}
function renderAdmin(){const revenue=state.orders.reduce((s,o)=>s+o.total,0);$('#orderCount').textContent=state.orders.length;$('#productCount').textContent=state.products.length;$('#revenue').textContent=money(revenue);$('#adminOrders').innerHTML=state.orders.slice().reverse().map(o=>`<div class="order-card"><div><h3>#${o.id} · ${o.name}</h3><select class="order-status" data-order="${o.id}"><option ${o.status==='Новый'?'selected':''}>Новый</option><option ${o.status==='В работе'?'selected':''}>В работе</option><option ${o.status==='Готов'?'selected':''}>Готов</option><option ${o.status==='Выдан'?'selected':''}>Выдан</option></select></div><p>${o.phone} · ${o.delivery}</p><p>${o.items.map(i=>`${i.name} × ${i.qty}`).join(', ')}</p><b>${money(o.total)}</b></div>`).join('')||'<div class="empty">Новых заказов пока нет.</div>';$('#adminProductList').innerHTML=state.products.map(p=>`<div class="admin-product"><div><h3>${p.name}</h3><p>${p.category} · ${money(p.price)} · остаток ${p.stock}</p></div><button data-edit="${p.id}">Изменить</button></div>`).join('')}
document.addEventListener('click',e=>{const view=e.target.closest('[data-view]');if(view)setView(view.dataset.view);const cat=e.target.closest('[data-category]');if(cat){state.category=cat.dataset.category;renderChips();renderProducts()}const add=e.target.closest('[data-add]');if(add){e.stopPropagation();addCart(add.dataset.add)}const fav=e.target.closest('[data-fav]');if(fav){e.stopPropagation();const id=Number(fav.dataset.fav);state.favorites=state.favorites.includes(id)?state.favorites.filter(x=>x!==id):[...state.favorites,id];save();renderProducts()}const pc=e.target.closest('[data-product]');if(pc&&!e.target.closest('button'))openProduct(pc.dataset.product);const close=e.target.closest('[data-close]');if(close){$(`#${close.dataset.close}`).classList.remove('open');document.dispatchEvent(new CustomEvent('parhub:modalchange'))}const qty=e.target.closest('[data-qty]');if(qty){const id=qty.dataset.qty;state.cart[id]=Math.max(0,Math.min((state.cart[id]||0)+Number(qty.dataset.delta),product(id).stock));if(!state.cart[id])delete state.cart[id];save();renderCart()}const edit=e.target.closest('[data-edit]');if(edit)editProduct(edit.dataset.edit)});
$('#filterBtn').onclick=()=>$('#filterPanel').classList.toggle('open');$('#searchToggle').onclick=()=>{$('#searchPanel').classList.toggle('open');$('#searchInput').focus()};$('#searchInput').oninput=e=>{state.search=e.target.value;renderProducts()};$('#sortSelect').onchange=e=>{state.sort=e.target.value;renderProducts()};$('#priceRange').oninput=e=>{state.maxPrice=Number(e.target.value);$('#priceValue').textContent=money(state.maxPrice);renderProducts()};$('#inStockOnly').onchange=e=>{state.inStock=e.target.checked;renderProducts()};$('#showHits').onclick=()=>{state.sort='popular';$('#sortSelect').value='popular';document.querySelector('.section-head').scrollIntoView({behavior:'smooth'})};
$('#checkoutBtn').onclick=()=>{if(!window.ParHubTelegram?.requireAuth())return;$('#checkoutModal').classList.add('open');document.dispatchEvent(new CustomEvent('parhub:modalchange'))};$('#checkoutForm').onsubmit=e=>{e.preventDefault();const fd=new FormData(e.target),items=Object.entries(state.cart).map(([id,qty])=>({...product(id),qty})),total=items.reduce((s,i)=>s+i.price*i.qty,0);state.orders.push({id:String(Date.now()).slice(-6),telegramUserId:window.ParHubTelegram?.user?.id||null,name:fd.get('name'),phone:fd.get('phone'),delivery:fd.get('delivery'),comment:fd.get('comment'),items,total,status:'Новый',createdAt:new Date().toISOString()});items.forEach(i=>{product(i.id).stock-=i.qty});state.cart={};save();renderCart();renderProducts();e.target.reset();$('#checkoutModal').classList.remove('open');toast('Заказ принят! Скоро свяжемся');setView('profile')};
let adminTaps=0,adminTapTimer;$('#profileAvatar').onclick=()=>{adminTaps++;clearTimeout(adminTapTimer);adminTapTimer=setTimeout(()=>adminTaps=0,1800);if(adminTaps===3)toast('Ещё 2 нажатия');if(adminTaps>=5){adminTaps=0;clearTimeout(adminTapTimer);setView('admin')}};$$('[data-admin-tab]').forEach(b=>b.onclick=()=>{$$('[data-admin-tab]').forEach(x=>x.classList.remove('active'));b.classList.add('active');$('#adminOrders').classList.toggle('hidden',b.dataset.adminTab!=='orders');$('#adminProducts').classList.toggle('hidden',b.dataset.adminTab!=='products')});document.addEventListener('change',e=>{if(e.target.matches('[data-order]')){state.orders.find(o=>o.id===e.target.dataset.order).status=e.target.value;save();toast('Статус обновлён')}});
function editProduct(id){const p=id?product(id):null,form=$('#productForm');form.reset();form.elements.id.value=p?.id||'';form.elements.name.value=p?.name||'';form.elements.category.value=p?.category||'Одноразовые';form.elements.flavor.value=p?.flavor||'';form.elements.price.value=p?.price||'';form.elements.stock.value=p?.stock??'';$('#editProductTitle').textContent=p?'Редактировать товар':'Новый товар';$('#editProductModal').classList.add('open');document.dispatchEvent(new CustomEvent('parhub:modalchange'))}
$('#addProductBtn').onclick=()=>editProduct();$('#productForm').onsubmit=e=>{e.preventDefault();const fd=new FormData(e.target),id=Number(fd.get('id'))||Date.now(),old=product(id),data={id,name:fd.get('name'),category:fd.get('category'),flavor:fd.get('flavor'),price:Number(fd.get('price')),stock:Number(fd.get('stock')),badge:old?.badge||'NEW',color:old?.color||'#a646e7',popular:old?.popular||1};if(old)Object.assign(old,data);else state.products.push(data);save();renderChips();renderProducts();renderAdmin();$('#editProductModal').classList.remove('open');toast('Товар сохранён')};
if(!localStorage.getItem('ph-age'))$('#ageGate').classList.add('open');$('#confirmAge').onclick=()=>{localStorage.setItem('ph-age','yes');$('#ageGate').classList.remove('open')};$('#denyAge').onclick=()=>{document.querySelector('.age-card').innerHTML='<h1>Доступ ограничен</h1><p>Каталог доступен только совершеннолетним пользователям.</p>'};
renderChips();renderProducts();renderCart();
